### PR TITLE
Metadata

### PR DESCRIPTION
**Pull request by untitaker**
- [x] tests -- **no CLI tests but eh**
  - [ ] fault tolerance -- what about invalid colors? -- **not sure, should filesystem storage start validating stuff?**
  - [x] better docs regarding `vdirsyncer metasync` usage
  - [x] Should vdirsyncer crash if changes couldn't be applied, or just ignore and revert on other side? -- **DAV is playing stupid and I couldn't find a server in our testsuite that doesn't accept literally anything, delayed**

### CODE REVIEW

**Comment by geier** [comment]
invalid colors: no, I don't think that should concern vdirsyncer, I think you always should try to reproduce the server content as faithfully as possible.

I'm not really sure yet what is the best way to support colors, but displayname should be no problem.

**Comment by untitaker** [comment]
Right, but I mean the other direction: The user is able to enter arbitrary values into those files, I thought they might get bizarre behavior or nondescriptive error messages because of that (the user shouldn't really have to look at the HTTP log to find out what's wrong, sadly this is often required with DAV). But it turns out that e.g. ownCloud literally accepts any string as value (I haven't checked how broken values are handled in the web UI)

On 10 July 2015 01:00:30 CEST, Christian Geier <notifications@github.com> wrote:
>invalid colors: no, I don't think that should concern vdirsyncer, I
>think you always should try to reproduce the server content as
>faithfully as possible.
>
>I'm not really sure yet what is the best way to support colors, but
>displayname should be no problem.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/pull/227#issuecomment-120170164

-- 
Sent from my phone. Please excuse my brevity.

**Comment by geier** [comment]
it looks like it was too late for me...

Quoting Markus Unterwaditzer (2015-07-10 01:05:20)
> Right, but I mean the other direction: The user is able to enter arbitrary values into those files, I thought they might get bizarre behavior or nondescriptive error messages because of that (the user shouldn't really have to look at the HTTP log to find out what's wrong, sadly this is often required with DAV). But it turns out that e.g. ownCloud literally accepts any string as value (I haven't checked how broken values are handled in the web UI)
>

**Comment by untitaker** [comment]
What do you mean? This PR is closed, but the new version isn't yet released.

On 10 July 2015 18:27:06 CEST, Christian Geier <notifications@github.com> wrote:
>
>it looks like it was too late for me...
>
>Quoting Markus Unterwaditzer (2015-07-10 01:05:20)
>> Right, but I mean the other direction: The user is able to enter
>arbitrary values into those files, I thought they might get bizarre
>behavior or nondescriptive error messages because of that (the user
>shouldn't really have to look at the HTTP log to find out what's wrong,
>sadly this is often required with DAV). But it turns out that e.g.
>ownCloud literally accepts any string as value (I haven't checked how
>broken values are handled in the web UI)
>> 
>> On 10 July 2015 01:00:30 CEST, Christian Geier
><notifications@github.com> wrote:
>> >invalid colors: no, I don't think that should concern vdirsyncer, I
>> >think you always should try to reproduce the server content as
>> >faithfully as possible.
>> >
>> >I'm not really sure yet what is the best way to support colors, but
>> >displayname should be no problem.
>> >
>> >
>> >---
>> >Reply to this email directly or view it on GitHub:
>>
>>https://github.com/untitaker/vdirsyncer/pull/227#issuecomment-120170164
>> 
>> -- 
>> Sent from my phone. Please excuse my brevity.
>> 
>> ---
>> Reply to this email directly or view it on GitHub:
>>
>https://github.com/untitaker/vdirsyncer/pull/227#issuecomment-120170789
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/pull/227#issuecomment-120451567

-- 
Sent from my phone. Please excuse my brevity.

**Comment by geier** [comment]
I meant I was too tired to think about this properly, sorry for the
confusion

Quoting Christian Geier (2015-07-10 18:13:13)
> 
> it looks like it was too late for me...
> 
> Quoting Markus Unterwaditzer (2015-07-10 01:05:20)
> > Right, but I mean the other direction: The user is able to enter arbitrary values into those files, I thought they might get bizarre behavior or nondescriptive error messages because of that (the user shouldn't really have to look at the HTTP log to find out what's wrong, sadly this is often required with DAV). But it turns out that e.g. ownCloud literally accepts any string as value (I haven't checked how broken values are handled in the web UI)
> >

**Comment by untitaker** [comment]
Opened https://github.com/untitaker/vdirsyncer/issues/230 for this, but I'm going to leave it like that for now.

**Pull request merged**
