### PR TITLE
Mention todoman as a supported client.

### PR DESCRIPTION
**Pull request by hobarrera**
This is a bit of a shameless plug, but I *did* design todoman with vdirsyncer support in mind, and there doesn't seem to by anything else listed to cover these requirements. 😄

Thanks for vdirsyncer, BTW, it did make it possible for me to *finally* organize my list of todos.

### CODE REVIEW

**Comment by untitaker** [comment]
Neat, thanks!

I'm currently using [watdo](https://github.com/untitaker/watdo) for this and like it, but others say that it's interface is kinky, so I'd always hoped that somebody would step up and write an alternative (I probably should mention watdo in the docs too).

I've found a minor issue with your current code, it's not writing the .ics-files [atomically](https://stackoverflow.com/questions/2705076/difference-between-writing-to-file-atomically-and-not). I've mentioned this in [the docs](https://vdirsyncer.readthedocs.org/en/stable/vdir.html), but don't really do a good job explaining it ATM. Take a look in [vdirsyncer's code](https://github.com/untitaker/vdirsyncer/blob/master/vdirsyncer/storage/filesystem.py#L144) to see how I implemented it.

**Comment by hobarrera** [comment]
Never came across watdo before. It's definitely worth mentioning as well (people might be interested). Though I think event-oriented CalDav clients should be separated from todo-oriented clients if we start having too many.

Atomicity when writing slipped my mind, but I'll put it high up in my priority list.

Hope you enjoy the interface though. :)

**Comment by hobarrera** [comment]
Huh, nice. I was already expecting to have to create a tmp-file, hardlink to it, and then clean up.

Looks like atomic_writer does all the work for me, thanks!

**Comment by untitaker** [comment]
I've now restructured the docs.

I'm currently trying to get todoman running and have run into a few issues. Should I report those on the GitHub project or on your own one?

**Comment by hobarrera** [comment]
Opening an issue on the [issue tracker](https://git.barrera.io/hobarrera/todoman/issues) is fine. I'll look into them ASAP.

**Pull request merged**
