### PR TITLE
ssl: support client certificates

### PR DESCRIPTION
**Pull request by mathstuf**
---
Tested with Davical+nginx locally.

### CODE REVIEW

**Comment by mathstuf** [comment]
Addresses #182.

**Comment by untitaker** [comment]
Thanks for this patch!

* I think `auth_cert` is a more fitting name, because then all auth-related stuff starts with `auth_`. We also support JSON lists in the config, so only one param is needed, and the user can use both PEM and key/cert formats (see cert param in http://www.python-requests.org/en/latest/api/#requests.request)
* Please add an example to the docs you added, for both formats.
* Please also add this parameter to HttpStorage. There's also a shared docstring in there, ``HTTP_STORAGE_PARAMETERS``. Add some docs for that parameter there too.

**Comment by mathstuf** [comment]
Updated.

**Comment by untitaker** [comment]
Awesome, thanks!

**Pull request merged**
