### PR TITLE
handle a exception when the configuration is not correct

### PR DESCRIPTION
**Pull request by pierg75**
Trying vdirsyncer I made a wrong config file and I was getting some exceptions.
I added a better error message showing what could be wrong.

### CODE REVIEW

**Comment by untitaker** [comment]
Hello @pierg75, thanks for your contribution!

* Please remove the temporary binary file from your commit (see "files changed" tab)
* Please adhere to the styleguide. Your current code [has two violations](https://travis-ci.org/untitaker/vdirsyncer/jobs/58063142):

        pip install flake8
        flake8  # throws errors

* Catching `KeyError` around that much code is too broad IMO. Something inside `collections_for_pair` might raise this exception for completely unrelated reasons. I suppose the error message you got was from `all_storages[a_name]`, so this should work:

    ```diff
    +    try:
    +        config_a, config_b = all_storages[a_name], all_storages[b_name]
    +    except KeyError as e:
    +        raise CliError('Pair {}: Storage {} not found. These are the '
    +                       'configured storages: {}'
    +                       .format(pair_name, str(e), list(all_storages)))
    +
         all_collections = dict(collections_for_pair(
             general['status_path'], a_name, b_name, pair_name,
    -        all_storages[a_name], all_storages[b_name], pair_options
    +        config_a, config_b, pair_options
         ))
    ```
* It'd be nice if the error message is consistent with the one below it.

**Comment by pierg75** [comment]
Hi,
Indeed your suggestion works great :)
I've adjusted it based on your comment.

**Comment by untitaker** [comment]
Thanks!

**Comment by untitaker** [comment]
@pierg75 Please add yourself to `AUTHORS.rst` if you want.

**Comment by pierg75** [comment]
Thanks, but I think I still don't deserve to be there.
Maybe later when hopefully I'll push more changes :)

**Pull request merged**
