### PR TITLE
Replace instances of envvar TRAVIS with CI

### LINKED ISSUE #360: Replace all instances of TRAVIS envvar with CI
See https://github.com/untitaker/vdirsyncer/commit/25a2896f126252b14ca9ceb1488028a42ae6b8bd#commitcomment-16499897

### PR DESCRIPTION
**Pull request by hobarrera**
Fixes #360

### CODE REVIEW

**Comment by hobarrera** [comment]
@untitaker: Do you have a bot that adds the `in progress` label, or did you ninja-add it in less than one second?

**Comment by untitaker** [comment]
That's waffle.io, also runs at khal. I'm just trying it out.

**Comment by untitaker** [comment]
This will not suffice btw, usage of TRAVIS is also scattered across all testserver repos in the vdirsyncer org.

Build will go green anyway because both envvars exist.

**Comment by untitaker** [comment]
Thanks!

**Pull request merged**
