### PR TITLE
Add servers as submodules

### LINKED ISSUE #377: Make server builds fully reproducible
I am thinking of including the server repositories at https://github.com/vdirsyncer in the form of git submodules, instead of cloning them.

Since submodules are always defining a commit hash, it would make reproducible builds possible: People presumably get the same test result if they check the same hash out.

Another idea would be to start inlining most repos into the main repo, but this would require that we slim down the ownCloud and Baikal repos quite a bit.

Opinions?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/31767374-make-server-builds-fully-reproducible?utm_campaign=plugin&utm_content=tracker%2F574345&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F574345&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by untitaker**
Fix #377

### CODE REVIEW

**Comment by untitaker** [comment]
@homu r+

**Comment by hobarrera** [comment]
Would this be enough to close #377?

**Comment by untitaker** [comment]
You're right, I forgot.

**Comment by untitaker** [comment]
@homu r+

**Comment by hobarrera** [comment]
> Fix #378

Wrong issue number. ;)

**Comment by untitaker** [comment]
Thanks, fixed.

**Comment by untitaker** [comment]
@homu r+

**Pull request merged**
