### PR TITLE
Add prettier message when syncing inexistent pair

### LINKED ISSUE #345: `vdirsyncer sync foo` shows ugly error message if `foo` doesn't exist.
<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/31377819-vdirsyncer-sync-foo-shows-ugly-error-message-if-foo-doesn-t-exist?utm_campaign=plugin&utm_content=tracker%2F574345&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F574345&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by hobarrera**
Fixes #345

### CODE REVIEW

**Comment by untitaker** [comment]
Thanks! Test fail though, you need to create a config first.

**Comment by hobarrera** [comment]
Yes, I noticed I broke a test but didn't get around to fixing it last night. I'll see if I can narrow down how I broke them later today. (feedback is welcome if it's more obvious to you though).

**Comment by hobarrera** [comment]
Never mind, I had a dumb typo. It works now.

**Comment by untitaker** [comment]
Interesting, credentials for the Davical server are not available on forks.

I will need to look into skipping those tests if the credentials are missing.

**Comment by untitaker** [comment]
Thanks!

**Pull request merged**
