### PR TITLE
Add davical tests to Travis

### LINKED ISSUE #23: Integrate Davical into testsuite
<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5400353-integrate-davical-into-testsuite?utm_campaign=plugin&utm_content=tracker%2F574345&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F574345&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by untitaker**
Fix #23

### CODE REVIEW

**Comment by untitaker** [comment]
cc @geier

**Comment by untitaker** [comment]
I've ran those tests locally already (against @geier's server) and encountered absolutely no failures.

**Comment by untitaker** [comment]
BTW the code for the davical setup can be found here (as always): https://github.com/vdirsyncer/davical-testserver

**Comment by geier** [comment]
cpu wise, running those tests is no problem for my machine, not sure about bandwidth, but I believe that should be okay, too. I have no problem with the url being public at all, I used to host some public stuff there as well.

log

**Comment by untitaker** [comment]
@geier Good to hear. However, recently `brutus.lostpackets.de` looses all packets for me, and that for quite a while. It doesn't look like a simple IP reassignment (which I get for my provider too).

**Comment by geier** [comment]
My dyndns provider is moving servers, something seems to have gone wrong. I hope it's fixed soon.

**Pull request merged**
